---

################################################################################
# Configure the storage device
################################################################################

  - include_tasks: wipe_storage.yaml

  - include_tasks: format_storage.yaml
