---

################################################################################
# Cleanup
################################################################################

  - name: Delete the /prov folder
    file:
      path: "{{ working_directory }}/mnt/prov"
      state: absent

################################################################################
# Configure the user account
################################################################################

  - name: Create the user account
    include_tasks: configure_user.yaml

  - name: Delete the provisioning user account
    command: chroot "{{ working_directory }}/mnt" /bin/bash -c 'userdel -r {{ provisioner_login_username }}'

################################################################################
# Configure the hostname
################################################################################

  - name: Set the hostname
    include_tasks: configure_hostname.yaml

################################################################################
# Ensure netplan configuration is active
################################################################################

  - name: Check if netplan config backup file exists
    stat:
      path: "{{ working_directory }}/mnt/etc/netplan/01-network-manager-all.yaml.dpkg-backup"
    register: netplan_backup_file

  - name: Restore netplan config that was automatically backed up
    when: netplan_backup_file.stat.exists
    copy:
      src: "{{ working_directory }}/mnt/etc/netplan/01-network-manager-all.yaml.dpkg-backup"
      dest: "{{ working_directory }}/mnt/etc/netplan/01-network-manager-all.yaml"
      mode: 0600
