---

################################################################################
# Configure the boot partition
################################################################################

  - name: Install utility packages needed for configuring boot partition
    command: chroot "{{ working_directory }}/mnt" /bin/bash -c 'DEBIAN_FRONTEND=noninteractive apt-get install -qy rsync grub-efi-amd64'

  - name: Move boot files from root partition to boot partition
    command: chroot "{{ working_directory }}/mnt" /bin/bash -c 'rsync -r --no-links --info=skip0 /boot/ /boot/efi/.'

  - name: Edit GRUB configuration parameters
    blockinfile:
      path: "{{ working_directory }}/mnt/etc/default/grub"
      block: |
        GRUB_TIMEOUT=2
        GRUB_TIMEOUT_STYLE=hidden
        GRUB_DISABLE_OS_PROBER=true
        GRUB_HIDDEN_TIMEOUT_QUIET=true

  - name: Unmount the image
    include_tasks: unmount_device.yaml
    
  - name: Generate new partition UUID's and update GRUB 
    include_tasks: update_grub.yaml
    vars:
      partition_prefix: "p"
      
  - name: Remount the image
    include_tasks: mount_device.yaml
    vars:
      device_name: "{{ storage_device_name }}"
      partition_prefix: "p"
