---

################################################################################
# Validate usb_device_name
################################################################################

  - name: Ensure usb_device_name is set
    when: usb_device_name is not defined or usb_device_name | trim == ''
    fail:
      msg: "Must provide the name of the USB device that is to be provisioned"

  - name: Register the stats for the USB device file
    stat:
      path: "/dev/{{ usb_device_name }}"
    register: usb_device_check

  - name: Check if the USB device exists
    when: usb_device_check.stat is not defined or not usb_device_check.stat.exists
    fail:
      msg: "The device /dev/{{ usb_device_name }} does not exist!"

################################################################################
# Ensure the required config parameters have been set
################################################################################

  - name: Ensure working_directory is set
    when: working_directory is not defined or working_directory | trim  == ''
    fail:
      msg: "Must provide a value for working_directory"

  - name: Ensure provisioner_hostname is set
    when: provisioner_hostname is not defined or provisioner_hostname | trim == ''
    fail:
      msg: "Must provide a value for provisioner_hostname"

  - name: Ensure target_hostname is set
    when: target_hostname is not defined or target_hostname | trim == ''
    fail:
      msg: "Must provide a value for target_hostname"

  - name: Ensure provisioner_root_size_pct is set
    assert:
      that: provisioner_root_size_pct | int != None
      fail_msg: "Must provide a valid value for provisioner_root_size_pct"

  - name: Ensure target_root_size_pct is set
    assert:
      that: target_root_size_pct | int != None
      fail_msg: "Must provide a valid value for target_root_size_pct"

  - name: Ensure os_version_number is set
    when: os_version_number is not defined or os_version_number | trim == ''
    fail:
      msg: "Must provide a value for os_version_number"

  - name: Ensure os_version_name is set
    when: os_version_name is not defined or os_version_name | trim == ''
    fail:
      msg: "Must provide a value for os_version_name"

  - name: Ensure kernel_version is set
    when: kernel_version is not defined or kernel_version | trim == ''
    fail:
      msg: "Must provide a value for kernel_version"

  - name: Ensure target_eth_name is set
    when: target_eth_name is not defined or target_eth_name | trim == ''
    fail:
      msg: "Must provide a value for target_eth_name"

  - name: Ensure target_wifi_name is set
    when: target_wifi_name is not defined or target_wifi_name | trim == ''
    fail:
      msg: "Must provide a value for target_wifi_name"

  - name: Ensure ntp_server is set
    when: ntp_server is not defined or ntp_server | trim == ''
    fail:
      msg: "Must provide a value for ntp_server"
